seed: -1
task: "a1"
print_config: False
rl_device: "cuda:0"
sim_device: "cuda:0"
graphics_device: "cuda:0"
headless: False
logdir: "default"

env:
  num_envs: 4096
  env_spacing: 8.0
  send_timeouts: True  # For value bootstrap.
  episode_length_s: 20

  camera_params:
    focal_length: 100
    cam_height: 256
    cam_width: 256
    cam_xyz_offset: [0.26, 0.0, 0.03]
    cam_rpy_offset: [1.571, 1.571, 3.142]

observations:
  critic:
    observations: [
      BASE_LIN_VEL, BASE_ANG_VEL, PROJECTED_GRAVITY, VELOCITY_COMMANDS,
      DOF_POS, DOF_VEL, ACTIONS, RAY_CAST, BASE_MASS_SCALED,
      DOF_FRICTION_CURRICULUM_VALUES, PUSHING_FORCES, PUSHING_TORQUES,
      HIP_HEIGHTS, BASE_HEIGHT, FEET_AIR_TIME, FEET_CONTACT_TIME, FEET_CONTACT,
      STIFFNESS, DAMPING, MOTOR_STRENGTH
    ]
  policy:
    add_noise: True
    add_latency: True
    latency_resampling_interval_s: 3.0
    observations: [
      BASE_ANG_VEL, PROJECTED_GRAVITY,
      VELOCITY_COMMANDS, DOF_POS, DOF_VEL, ACTIONS
    ]
    sync_latency: [
      BASE_ANG_VEL, PROJECTED_GRAVITY,
      VELOCITY_COMMANDS, DOF_POS, DOF_VEL
    ]

symmetries:
  policy:
    symmetries: [
      BASE_ANG_VEL, PROJECTED_GRAVITY, VELOCITY_COMMANDS,
      A1_DOF_POS, A1_DOF_VEL, A1_ACTIONS
    ]
  actions:
    symmetries: [
      A1_ACTIONS, A1_STIFFNESS, A1_DAMPING
    ]

terrain:
  scene_root: "{GAUSS_GYM_ROOT_DIR}/scenes"
  cams_yaw_only: False
  max_traj_pos_distance: 1.0
  max_traj_yaw_distance_rad: 6.28
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.

  # Path to each scene, where each scene is a folder containing subfolders
  # 'meshes' and 'splatfacto'.
  scenes: [
    # /home/root-desktop/ARKitScenes/raw_ARKitScenes/3dod/Training/43895956/,
    # /home/root-desktop/ARKitScenes/raw_ARKitScenes/3dod/Training/43649417/,
    /home/root-desktop/ULI_DATA/apartment_to_grace/processed_data,
    /home/root-desktop/ULI_DATA/cute_bridge,
    /home/root-desktop/ULI_DATA/bww_stairs,
    /home/root-desktop/ULI_DATA/home_night,
    /home/root-desktop/ULI_DATA/washington,
    /home/root-desktop/ULI_DATA/long_stairs,
    /home/root-desktop/ULI_DATA/ryokan_bridge,
  ]


init_state:
  pos: [0.0, 0.0, 0.5]
  rot: [0.0, 0.0, 0.0, 1.0]
  lin_vel: [0.0, 0.0, 0.0]
  ang_vel: [0.0, 0.0, 0.0]
  default_joint_angles: {
    "FL_hip_joint": 0.1,
    "RL_hip_joint": 0.1,
    "FR_hip_joint": -0.1,
    "RR_hip_joint": -0.1,
    "FL_thigh_joint": 0.8,
    "RL_thigh_joint": 1.0, 
    "FR_thigh_joint": 0.8,
    "RR_thigh_joint": 1.0,
    "FL_calf_joint": -1.5,
    "RL_calf_joint": -1.5,
    "FR_calf_joint": -1.5,
    "RR_calf_joint": -1.5,
  }

control:
  control_type: "P"
  stiffness: {
    "joint": 50.0
  }
  damping: {
    "joint": 1.0
  }
  action_scale: 0.5
  decimation: 4
  torque_limits: 25
  computer_clip_torque: True
  motor_clip_torque: False

asset:
  file: "{GAUSS_GYM_ROOT_DIR}/resources/robots/a1/urdf/a1.urdf"
  mujoco_file: "{GAUSS_GYM_ROOT_DIR}/resources/robots/a1/xml/a1.xml"
  name: "a1"
  base_link_name: "base"
  camera_link_name: "base"
  foot_name: "foot"
  hip_link_names: ["FR_hip", "FL_hip", "RR_hip", "RL_hip"]
  front_hip_names: ["FR_hip_joint", "FL_hip_joint"]
  rear_hip_names: ["RR_hip_joint", "RL_hip_joint"]
  penalize_contacts_on: ["thigh", "calf", "hip"]
  terminate_after_contacts_on: ["base", "imu"]
  feet_edge_pos: [[0.0, 0.0, 0.0]]
  feet_contact_radius: 0.0201

  disable_gravity: False
  collapse_fixed_joints: True
  fix_base_link: False
  default_dof_drive_mode: 3
  self_collisions: 1
  replace_cylinder_with_capsule: True
  flip_visual_attachments: True

  density: 0.001
  angular_damping: 0.
  linear_damping: 0.
  max_angular_velocity: 1000.
  max_linear_velocity: 1000.
  armature: 0.
  thickness: 0.01

curriculum:
  apply_curriculum: True

  dof_friction:
    apply: True
    # epochs: 10000
    epochs: 3000
    update_every: 10
    start: 0.1
    end: 0.0
    sample_type: "uniform"

domain_rand:
  apply_domain_rand: True

  init_dof_pos:
    apply: True
    range: [0.0, 0.05]
    operation: "additive"
    distribution: "gaussian"
  init_base_lin_vel_xy:
    apply: True
    range: [0.0, 0.1]
    operation: "additive"
    distribution: "gaussian"
  init_base_yaw:
    apply: True
    range: [0.0, 1.5]
    operation: "additive"
    distribution: "gaussian"

  base_com_x:
    apply: True
    range: [-0.1, 0.1]
    operation: "additive"
    distribution: "uniform"
  base_com_y:
    apply: True
    range: [-0.1, 0.1]
    operation: "additive"
    distribution: "uniform"
  base_com_z:
    apply: True
    range: [-0.05, 0.05]
    operation: "additive"
    distribution: "uniform"
  base_mass:
    apply: True
    range: [0.8, 1.2]
    operation: "scaling"
    distribution: "uniform"
  other_com:
    apply: True
    range: [-0.005, 0.005]
    operation: "additive"
    distribution: "uniform"
  other_mass:
    apply: True
    range: [0.9, 1.1]
    operation: "scaling"
    distribution: "uniform"

  motor_strength:
    apply: True
    range: [0.9, 1.1]
    operation: "scaling"
    distribution: "uniform"

  dof_stiffness:
    apply: True
    range: [0.9, 1.1]
    operation: "scaling"
    distribution: "uniform"
  dof_damping:
    apply: True
    range: [0.95, 1.05]
    operation: "scaling"
    distribution: "uniform"
  dof_damping_ankles:
    apply: False
    ankle_names: ["Left_Ankle_Pitch", "Right_Ankle_Pitch", "Left_Ankle_Roll", "Right_Ankle_Roll"]
    range: [-0.5, 2.0]
    operation: "additive"
    distribution: "uniform"
  dof_friction:
    apply: False
    range: [0.0, 2.0]
    operation: "additive"
    distribution: "uniform"
  dof_friction_ig_property:
    apply: False
    range: [0.0, 0.05]
    operation: "additive"
    distribution: "uniform"
  dof_armature_ig_property:
    apply: True
    range: [0.01, 0.015]
    operation: "additive"
    distribution: "uniform"

  foot_friction:
    apply: True
    range: [0.3, 2.0]
    operation: "additive"
    distribution: "uniform"
  foot_compliance:
    apply: True
    range: [0.5, 1.5]
    operation: "additive"
    distribution: "uniform"
  foot_restitution:
    apply: True
    range: [0.1, 0.9]
    operation: "additive"
    distribution: "uniform"

  kick_interval_s: 4.0
  kick_lin_vel:
    apply: True
    range: [-1.5, 1.5]
    operation: "additive"
    distribution: "uniform"
  kick_ang_vel:
    apply: True
    range: [-1.5, 1.5]
    operation: "additive"
    distribution: "uniform"

  push_interval_s: 8.0
  push_duration_s: 1.0
  push_force:
    apply: True
    range: [0., 10.]
    operation: "additive"
    distribution: "gaussian"
  push_torque:
    apply: True
    range: [0., 2.]
    operation: "additive"
    distribution: "gaussian"

termination:
  base_height_threshold: 0.08
  projected_gravity_z_threshold: 0.0

# rewards:
#   only_positive_rewards: True

#   tracking_lin_vel_x:
#     scale: 4.0
#     tracking_sigma: 0.25
#   tracking_lin_vel_y:
#     scale: 4.0
#     tracking_sigma: 0.25
#   tracking_ang_vel:
#     scale: 2.0
#     tracking_sigma: 0.25
#   lin_vel_z:
#     scale: -0.5
#   ang_vel_xy:
#     scale: -0.05
#   torques:
#     scale: -0.00005
#   feet_air_time:
#     scale: 1.0
#     min_air_time: 0.3
#     max_air_time: 0.4
#   collision:
#     scale: -1.0
#   action_rate:
#     scale: -0.005
#   hip_height_l1:
#     scale: 1.0
#     min_height: 0.3
#     max_height: 0.31
#   dof_pos_limits:
#     scale: -1.0
#     soft_dof_pos_limit: 1.0
#   energy_substeps:
#     scale: -0.0005
#   feet_clearance_clipped:
#     scale: 4.0
#     clearance_height: 0.1
#   # feet_clearance_2:
#   #   scale: -1.0
#   #   clearance_height: 0.1
#   feet_slip:
#     scale: -0.1
#   # delta_torques:
#   #   scale: -1.e-5
#   # a1_pose:
#   #   scale: 0.5


rewards:
  only_positive_rewards: True

  tracking_lin_vel_x:
    scale: 1.0
    tracking_sigma: 0.25
  tracking_lin_vel_y:
    scale: 1.0
    tracking_sigma: 0.25
  tracking_ang_vel:
    scale: 0.5
    tracking_sigma: 0.25
  lin_vel_z:
    scale: -2.0
  ang_vel_xy:
    scale: -0.05
  dof_acc:
    scale: -2.5e-7
  torques:
    scale: -0.0001
  feet_air_time:
    scale: 1.0
    min_air_time: 0.5
    max_air_time: 100.0
  collision:
    scale: -1.0
  action_rate:
    scale: -0.01
  a1_pose:
    scale: 0.25

commands:
  still_proportion: 0.05
  command_gains: False
  command_gains_stiffness_range: [0.4, 1.6]
  command_gains_damping_range: [0.4, 1.6]
  heading_command: True
  num_commands: 4
  resampling_time: 4. # time before command are changed[s]
  small_lin_vel_threshold: 0.0
  small_ang_vel_threshold: 0.0
  ranges:
    lin_vel: [0.1, 1.0]
    ang_vel_yaw: [-1, 1]
    heading: [-3.14, 3.14]

normalization:
  filter_weight: 0.2
  clip_actions: 100.0
  clip_actions_method: "normal"
  dof_pos_redundancy: 0.2
  const_dof_range: {
    Hip_max: 0.802,
    Hip_min: -0.802,
    Thigh_max: 4.19,
    Thigh_min: -1.05,
    Calf_max: -0.916,
    Calf_min: -2.7
  }
  sim_sdk_map: {
    "FL_hip_joint": "Hip",
    "FL_thigh_joint": "Thigh",
    "FL_calf_joint": "Calf",
    "FR_hip_joint": "Hip",
    "FR_thigh_joint": "Thigh",
    "FR_calf_joint": "Calf",
    "RL_hip_joint": "Hip",
    "RL_thigh_joint": "Thigh",
    "RL_calf_joint": "Calf",
    "RR_hip_joint": "Hip",
    "RR_thigh_joint": "Thigh",
    "RR_calf_joint": "Calf"
  }

viewer:
  ref_env: 0
  pos: [10., 0., 6.]
  lookat: [11., 5., 3.]

sim:
  physics_engine: "SIM_PHYSX" # or "SIM_FLEX"
  dt: 0.005
  substeps: 1
  gravity: [0.0, 0.0, -9.81]
  up_axis: 1

  physx:
    num_subscenes: 0
    num_threads: 10
    solver_type: 1
    num_position_iterations: 4
    num_velocity_iterations: 0
    contact_offset: 0.01
    rest_offset: 0.0
    bounce_threshold_velocity: 0.5
    max_depenetration_velocity: 1.0
    max_gpu_contact_pairs: 8_388_608 # 2^23
    default_buffer_size_multiplier: 5
    contact_collection: 2

policy:
  class_name: "RecurrentModel"
  learning_rate: 1.e-5
  desired_kl: 0.01
  kl_key: "actions"
  obs_key: "policy"
  params:
    layer_activation: "elu"
    recurrent_state_size: 256
    hidden_layer_sizes: [256, 128]
    symlog_inputs: True
    normalize_obs: True
    head:
      actions: {output_type: normal_logstdparam_unclipped, minstd: 0.2, maxstd: 1.0, outscale: 1.0, init_std: 0.9}
      stiffness: {output_type: bounded_normal_logstdparam_unclipped, minstd: 0.05, maxstd: 1.0, outscale: 1.0, init_std: 0.3}
      damping: {output_type: bounded_normal_logstdparam_unclipped, minstd: 0.05, maxstd: 1.0, outscale: 1.0, init_std: 0.3}

value:
  class_name: "RecurrentModel"
  learning_rate: 3.e-4
  obs_key: "critic"
  params:
    layer_activation: "elu"
    recurrent_state_size: 512
    hidden_layer_sizes: [512, 256, 128]
    symlog_inputs: True
    normalize_obs: True
    head: 
      value: {output_type: mse, outscale: 1.0}

algorithm:
  gamma: 0.97
  lam: 0.95
  actor_loss_coefs:
    actions: 1.0
    stiffness: 0.25
    damping: 0.25
  entropy_coefs:
    actions: -0.01
    stiffness: -0.001
    damping: -0.001
  symmetry: True
  symmetry_coefs:
    actions: 3.0
    stiffness: 3.0
    damping: 3.0
  num_learning_epochs: 5
  num_mini_batches: 4
  value_loss_coef: 1.0
  use_clipped_value_loss: False
  clip_param: 0.2
  bound_coefs:
    actions: 1.0
  normalize_advantage_per_minibatch: True

runner:
  record_video: True
  record_distance: [-1.8, -1.8, 0.5]
  num_steps_per_env: 24
  class_name: "Runner"
  use_wandb: True
  description: ""
  log_every: 30.
  save_every: 600.
  record_every: 600.
  record_frames: 300.
  run_name: ""
  resume: False
  load_run: ""
  checkpoint: -1
  resume_path: ""
  max_iterations: 10000
