seed: -1
task: "a1"
print_config: False
rl_device: "cuda:0"
sim_device: "cuda:0"
headless: False
logdir: "default"

env:
  num_envs: 4096
  env_spacing: 8.0
  send_timeouts: True  # For value bootstrap.
  episode_length_s: 20

  camera_params:
    focal_length: 40
    cam_height: 64
    cam_width: 64
    cam_xyz_offset: [0.26, 0.0, 0.03]
    cam_rpy_offset: [1.571, 1.571, 3.142]

observations:
  teacher_observations:
    observations: [
      BASE_LIN_VEL, BASE_ANG_VEL, PROJECTED_GRAVITY, VELOCITY_COMMANDS,
      DOF_POS, DOF_VEL, ACTIONS, RAY_CAST, BASE_MASS_SCALED,
      DOF_FRICTION_CURRICULUM_VALUES, PUSHING_FORCES, PUSHING_TORQUES,
      HIP_HEIGHTS, BASE_HEIGHT]
  student_observations:
    add_noise: True
    add_latency: True
    latency_resampling_interval_s: 2.0
    observations: [
      BASE_ANG_VEL, PROJECTED_GRAVITY,
      VELOCITY_COMMANDS, DOF_POS, DOF_VEL, ACTIONS
    ]

terrain:
  scene_root: "{GAUSS_GYM_ROOT_DIR}/scenes"
  cams_yaw_only: False
  max_traj_pos_distance: 1.0
  max_traj_yaw_distance_rad: 1.0
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.


init_state:
  pos: [0.0, 0.0, 0.5]
  rot: [0.0, 0.0, 0.0, 1.0]
  lin_vel: [0.0, 0.0, 0.0]
  ang_vel: [0.0, 0.0, 0.0]
  default_joint_angles: {
    "FL_hip_joint": 0.1,
    "RL_hip_joint": 0.1,
    "FR_hip_joint": -0.1,
    "RR_hip_joint": -0.1,
    "FL_thigh_joint": 0.8,
    "RL_thigh_joint": 1.0, 
    "FR_thigh_joint": 0.8,
    "RR_thigh_joint": 1.0,
    "FL_calf_joint": -1.5,
    "RL_calf_joint": -1.5,
    "FR_calf_joint": -1.5,
    "RR_calf_joint": -1.5,
  }

control:
  control_type: "P"
  stiffness: {
    "joint": 50.0
  }
  damping: {
    "joint": 1.0
  }
  action_scale: 0.5
  decimation: 4
  torque_limits: 25
  computer_clip_torque: True
  motor_clip_torque: False

asset:
  file: "{GAUSS_GYM_ROOT_DIR}/resources/robots/a1/urdf/a1.urdf"
  name: "a1"
  base_link_name: "base"
  camera_link_name: "base"
  foot_name: "foot"
  hip_link_names: ["FR_hip", "FL_hip", "RR_hip", "RL_hip"]
  front_hip_names: ["FR_hip_joint", "FL_hip_joint"]
  rear_hip_names: ["RR_hip_joint", "RL_hip_joint"]
  penalize_contacts_on: ["thigh", "calf", "hip"]
  terminate_after_contacts_on: ["base", "imu"]
  feet_edge_pos: [[0.0, 0.0, 0.0]]
  feet_contact_radius: 0.0201

  disable_gravity: False
  collapse_fixed_joints: True
  fix_base_link: False
  default_dof_drive_mode: 3
  self_collisions: 1
  replace_cylinder_with_capsule: True
  flip_visual_attachments: True

  density: 0.001
  angular_damping: 0.
  linear_damping: 0.
  max_angular_velocity: 1000.
  max_linear_velocity: 1000.
  armature: 0.
  thickness: 0.01

curriculum:
  apply_curriculum: True

  dof_friction:
    apply: True
    epochs: 10000
    update_every: 10
    start: 0.2
    end: 0.01
    sample_type: "uniform"

domain_rand:
  apply_domain_rand: True

  init_dof_pos:
    apply: False
    range: [0.0, 0.05]
    operation: "additive"
    distribution: "gaussian"
  init_base_lin_vel_xy:
    apply: False
    range: [0.0, 0.1]
    operation: "additive"
    distribution: "gaussian"

  base_com_x:
    apply: True
    range: [-0.15, 0.15]
    operation: "additive"
    distribution: "uniform"
  base_com_y:
    apply: True
    range: [-0.1, 0.1]
    operation: "additive"
    distribution: "uniform"
  base_com_z:
    apply: True
    range: [-0.05, 0.05]
    operation: "additive"
    distribution: "uniform"
  base_mass:
    apply: True
    range: [0.8, 1.2]
    operation: "scaling"
    distribution: "uniform"
  other_com:
    apply: True
    range: [-0.005, 0.005]
    operation: "additive"
    distribution: "uniform"
  other_mass:
    apply: True
    range: [0.98, 1.02]
    operation: "scaling"
    distribution: "uniform"

  dof_stiffness:
    apply: True
    range: [0.9, 1.1]
    operation: "scaling"
    distribution: "uniform"
  dof_damping:
    apply: True
    range: [0.95, 1.05]
    operation: "scaling"
    distribution: "uniform"
  dof_friction:
    apply: False
    range: [0.0, 2.0]
    operation: "additive"
    distribution: "uniform"

  foot_friction:
    apply: True
    range: [0.5, 1.25]
    operation: "additive"
    distribution: "uniform"
  foot_compliance:
    apply: True
    range: [0.5, 1.5]
    operation: "additive"
    distribution: "uniform"
  foot_restitution:
    apply: True
    range: [0.1, 0.9]
    operation: "additive"
    distribution: "uniform"

  kick_interval_s: 4.0
  kick_lin_vel:
    apply: True
    range: [0.0, 0.1]
    operation: "additive"
    distribution: "gaussian"
  kick_ang_vel:
    apply: True
    range: [0.0, 0.02]
    operation: "additive"
    distribution: "gaussian"

  push_interval_s: 5.0
  push_duration_s: 1.0
  push_force:
    apply: True
    range: [0.0, 6.0]
    operation: "additive"
    distribution: "gaussian"
  push_torque:
    apply: True
    range: [0.0, 1.5]
    operation: "additive"
    distribution: "gaussian"

rewards:
  only_positive_rewards: True
  tracking_sigma: 0.25
  soft_dof_pos_limit: 1.0
  soft_dof_vel_limit: 1.0
  soft_torque_limit: 1.0
  base_height_target: 0.25
  hip_height_target: 0.25
  max_contact_force: 100.0
  terminate_height: 0.08
  feet_air_time_min_time: 0.5
  feet_air_time_max_time: 1.0
  feet_contact_time_min_time: 0.2
  feet_contact_time_max_time: 0.5
  scales:
    tracking_lin_vel_x: 1.0
    tracking_lin_vel_y: 1.0
    tracking_ang_vel: 0.5
    lin_vel_z: -0.5
    ang_vel_xy: -0.05
    torques: -0.000033 # -0.00005 # -0.000033 # -0.0001 # -0.00001
    dof_acc: -2.5e-7
    feet_air_time:  1.0
    feet_contact_time: 1.0
    collision: -1.
    action_rate: -0.01
    hip_height: -1.0
    dof_pos_limits: -1.0

commands:
  still_proportion: 0.0
  heading_command: True
  num_commands: 4
  resampling_time: 10. # time before command are changed[s]
  small_lin_vel_threshold: 0.1
  small_ang_vel_threshold: 0.1
  ranges:
    lin_vel: [0.1, 1.0]
    lin_vel_yaw: [-1.0, 1.0]
    ang_vel_yaw: [-1, 1]
    heading: [-3.14, 3.14]

normalization:
  filter_weight: 0.2
  clip_actions: 100.0
  clip_actions_method: "normal"
  dof_pos_redundancy: 0.2
  const_dof_range: {
    Hip_max: 0.802,
    Hip_min: -0.802,
    Thigh_max: 4.19,
    Thigh_min: -1.05,
    Calf_max: -0.916,
    Calf_min: -2.7
  }
  sim_sdk_map: {
    "FL_hip_joint": "Hip",
    "FL_thigh_joint": "Thigh",
    "FL_calf_joint": "Calf",
    "FR_hip_joint": "Hip",
    "FR_thigh_joint": "Thigh",
    "FR_calf_joint": "Calf",
    "RL_hip_joint": "Hip",
    "RL_thigh_joint": "Thigh",
    "RL_calf_joint": "Calf",
    "RR_hip_joint": "Hip",
    "RR_thigh_joint": "Thigh",
    "RR_calf_joint": "Calf"
  }

viewer:
  ref_env: 0
  pos: [10., 0., 6.]
  lookat: [11., 5., 3.]
  record_video: False

sim:
  physics_engine: "SIM_PHYSX" # or "SIM_FLEX"
  dt: 0.005
  substeps: 1
  gravity: [0.0, 0.0, -9.81]
  up_axis: 1

  physx:
    num_subscenes: 0
    num_threads: 10
    solver_type: 1
    num_position_iterations: 4
    num_velocity_iterations: 0
    contact_offset: 0.01
    rest_offset: 0.0
    bounce_threshold_velocity: 0.5
    max_depenetration_velocity: 1.0
    max_gpu_contact_pairs: 8_388_608 # 2^23
    default_buffer_size_multiplier: 5
    contact_collection: 2

policy:
  init_noise_std: 0.5
  mu_activation: "identity"
  layer_activation: "elu"

algorithm:
  learning_rate: 1.e-5
  gamma: 0.99
  lam: 0.95
  entropy_coef: -0.01
  symmetric_coef: 10.0
  num_learning_epochs: 20
  clip_min_std: 0.2
  value_loss_coef: 1.0
  use_clipped_value_loss: True
  clip_param: 0.2
  bound_coef: 1.0
  desired_kl: 0.01

runner:
  num_steps_per_env: 24
  class_name: "Runner"
  policy_class_name: "ActorCriticRecurrent"
  use_wandb: False
  description: ""
  save_interval: 50
  run_name: ""
  resume: False
  load_run: ""
  checkpoint: -1
  resume_path: ""
  max_iterations: 10000
