seed: -1
task: "t1"
print_config: False
rl_device: "cuda:0"
sim_device: "cuda:0"
graphics_device: "cuda:0"
headless: False
logdir: "default"

env:
  num_envs: 4096
  env_spacing: 8.0
  send_timeouts: True  # For value bootstrap.
  episode_length_s: 20

  camera_params:
    focal_length: 100
    cam_height: 48
    cam_width: 48
    cam_xyz_offset: [0., 0., 0.]
    cam_rpy_offset: [1.571, 1.571, 3.142]

observations:
  teacher_observations:
    observations: [
      BASE_LIN_VEL, BASE_ANG_VEL, PROJECTED_GRAVITY,
      VELOCITY_COMMANDS, DOF_POS, DOF_VEL, ACTIONS,
      RAY_CAST, BASE_MASS_SCALED,
      DOF_FRICTION_CURRICULUM_VALUES,
      PUSHING_FORCES, PUSHING_TORQUES, GAIT_PROGRESS,
      HIP_HEIGHTS, BASE_HEIGHT, FEET_AIR_TIME, FEET_CONTACT_TIME, FEET_CONTACT
      ]
  student_observations:
    add_noise: True
    add_latency: False
    latency_resampling_interval_s: 3.0
    observations: [
      BASE_ANG_VEL, PROJECTED_GRAVITY,
      VELOCITY_COMMANDS, DOF_POS,
      DOF_VEL, ACTIONS, GAIT_PROGRESS
    ]
    sync_latency: [
      BASE_ANG_VEL, PROJECTED_GRAVITY,
      VELOCITY_COMMANDS, DOF_POS, DOF_VEL
    ]

symmetries:
  student_observations:
    symmetries: [
      BASE_ANG_VEL, PROJECTED_GRAVITY, VELOCITY_COMMANDS,
      T1_DOF_POS, T1_DOF_VEL, T1_ACTIONS, GAIT_PROGRESS
    ]
  actions:
    symmetries: [
      T1_ACTIONS
    ]

terrain:
  scene_root: "{GAUSS_GYM_ROOT_DIR}/scenes"
  cams_yaw_only: True
  max_traj_pos_distance: 1.0
  max_traj_yaw_distance_rad: 6.28
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.


init_state:
  pos: [0.0, 0.0, 0.86]
  rot: [0.0, 0.0, 0.0, 1.0]
  lin_vel: [0.0, 0.0, 0.0]
  ang_vel: [0.0, 0.0, 0.0]
  default_joint_angles: { # = target angles [rad] when action = 0.0
    'AAHead_yaw': 0.,
    'Head_pitch': 0.,
    'Left_Hip_Pitch': -0.2,
    'Left_Hip_Roll': 0.,
    'Left_Hip_Yaw': 0.,
    'Left_Knee_Pitch': 0.4,
    'Left_Ankle_Pitch': -0.25,
    'Left_Ankle_Roll': 0.0,
    'Right_Hip_Pitch': -0.2,
    'Right_Hip_Roll': 0.,
    'Right_Hip_Yaw': 0.,
    'Right_Knee_Pitch': 0.4,
    'Right_Ankle_Pitch': -0.25,
    'Right_Ankle_Roll': 0.0
  }

control:
  control_type: "P"
  stiffness: {
    'Head': 50.0,
    'Hip': 200.0, 
    'Knee': 200.0,
    'Ankle': 50.0
  }  # [N*m/rad]
  damping: {
    'Head': 1.0,
    'Hip': 5.0, 
    'Knee': 5.0,
    'Ankle': 1.0
  }
  action_scale: 1.0
  decimation: 10
  computer_clip_torque: False
  motor_clip_torque: False

asset:
  file: "{GAUSS_GYM_ROOT_DIR}/resources/robots/t1/urdf/T1_locomotion.urdf"
  mujoco_file: "{GAUSS_GYM_ROOT_DIR}/resources/robots/t1/urdf/T1_locomotion.xml"
  name: "t1"
  base_link_name: "Trunk"
  camera_link_name: "H2"
  foot_name: "foot_link"
  hip_link_names: ["Hip_Pitch_Left", "Hip_Pitch_Right"]
  front_hip_names: ["Left_Hip_Pitch", "Right_Hip_Pitch"]
  rear_hip_names: ["Left_Hip_Pitch", "Right_Hip_Pitch"]
  penalize_contacts_on: ["Trunk", "H1", "H2", "AL", "AR", "Waist", "Hip", "Shank", "Ankle"]
  terminate_after_contacts_on: ["Trunk"]
  feet_edge_pos: [[ 0.1215,  0.05, -0.03],
                  [ 0.1215, -0.05, -0.03],
                  [-0.1015,  0.05, -0.03],
                  [-0.1015, -0.05, -0.03]] # x,y,z [m]
  feet_contact_radius: 0.01

  disable_gravity: False
  collapse_fixed_joints: False
  fix_base_link: False
  default_dof_drive_mode: 3
  self_collisions: 0
  replace_cylinder_with_capsule: True
  flip_visual_attachments: False

  density: 0.001
  angular_damping: 0.
  linear_damping: 0.
  max_angular_velocity: 1000.
  max_linear_velocity: 1000.
  armature: 0.
  thickness: 0.01

curriculum:
  apply_curriculum: False

  dof_friction:
    apply: False
    epochs: 10000
    update_every: 10
    start: 0.12
    end: 0.02
    sample_type: "uniform"

domain_rand:
  apply_domain_rand: True

  init_dof_pos:
    apply: True
    range: [0.0, 0.05]
    operation: "additive"
    distribution: "gaussian"
  init_base_lin_vel_xy:
    apply: True
    range: [0.0, 0.1]
    operation: "additive"
    distribution: "gaussian"
  init_base_yaw:
    apply: True
    range: [0.0, 1.5]
    operation: "additive"
    distribution: "gaussian"

  base_com_x:
    apply: True
    range: [-0.1, 0.1]
    operation: "additive"
    distribution: "uniform"
  base_com_y:
    apply: True
    range: [-0.1, 0.1]
    operation: "additive"
    distribution: "uniform"
  base_com_z:
    apply: True
    range: [-0.1, 0.1]
    operation: "additive"
    distribution: "uniform"
  base_mass:
    apply: True
    range: [0.8, 1.2]
    operation: "scaling"
    distribution: "uniform"
  other_com:
    apply: True
    range: [-0.005, 0.005]
    operation: "additive"
    distribution: "uniform"
  other_mass:
    apply: True
    range: [0.9, 1.1]
    operation: "scaling"
    distribution: "uniform"

  dof_stiffness:
    apply: True
    range: [0.9, 1.1]
    operation: "scaling"
    distribution: "uniform"
  dof_damping:
    apply: True
    range: [0.95, 1.05]
    operation: "scaling"
    distribution: "uniform"
  dof_damping_ankles:
    apply: True
    ankle_names: ["Left_Ankle_Pitch", "Right_Ankle_Pitch", "Left_Ankle_Roll", "Right_Ankle_Roll"]
    range: [-0.5, 2.0]
    operation: "additive"
    distribution: "uniform"
  dof_friction:
    apply: True
    range: [0.0, 2.0]
    operation: "additive"
    distribution: "uniform"

  foot_friction:
    apply: True
    range: [0.3, 2.0]
    operation: "additive"
    distribution: "uniform"
  foot_compliance:
    apply: True
    range: [0.5, 1.5]
    operation: "additive"
    distribution: "uniform"
  foot_restitution:
    apply: True
    range: [0.1, 0.9]
    operation: "additive"
    distribution: "uniform"

  kick_interval_s: 5.0
  kick_lin_vel:
    apply: True
    range: [-2.0, 2.0]
    operation: "additive"
    distribution: "uniform"
  kick_ang_vel:
    apply: True
    range: [-2.0, 2.0]
    operation: "additive"
    distribution: "uniform"

  push_interval_s: 5.0
  push_duration_s: 1.0
  push_force:
    apply: True
    # range: [0., 30.]
    range: [0., 10.]
    operation: "additive"
    distribution: "gaussian"
  push_torque:
    apply: True
    # range: [0., 15.]
    range: [0., 2.]
    operation: "additive"
    distribution: "gaussian"

rewards:
  only_positive_rewards: True
  tracking_sigma: 0.15
  soft_dof_pos_limit: 1.0
  soft_dof_vel_limit: 1.0
  soft_torque_limit: 1.0
  base_height_target: 0.68
  base_height_target_max: 0.70
  max_contact_force: 500.0
  terminate_height: 0.45
  terminate_rotation: 0.0
  feet_air_time_min_time: 0.5
  feet_air_time_max_time: 1.0
  swing_period: 0.2
  feet_distance_ref: 0.2
  scales:
    survival: 0.25
    tracking_lin_vel_x: 2.0
    tracking_lin_vel_y: 2.0
    tracking_ang_vel: 1.0
    lin_vel_z: -0.5  # -2.
    ang_vel_xy: -0.2
    orientation: -1.0 # -5.
    # base_height: -1.0 # -20.  # Play with this.
    base_height_l1: 1.0
    torques: -0.0001 # -2.e-4
    action_rate: -0.1 # -1.
    dof_acc: -1.e-7
    dof_pos_limits: -1.
    collision: -1.

    # TODO: Do we need these?
    dof_vel: -1.e-4
    torque_tiredness: -1.e-2
    power: -2.e-3
    root_acc: -1.e-4
    feet_slip: -0.1
    feet_vel_z: -0.
    feet_yaw_diff: -1.
    feet_yaw_mean: -1.
    feet_roll: -0.1
    feet_distance: -1.
    feet_swing: 3.

commands:
  still_proportion: 0.0
  heading_command: True
  num_commands: 4
  resampling_time: 10. # time before command are changed[s]
  gait_frequency: [1.0, 2.0]
  small_lin_vel_threshold: 0.1
  small_ang_vel_threshold: 0.1
  ranges:
    lin_vel: [0.0, 1.0]
    ang_vel_yaw: [-1, 1]
    heading: [-3.14, 3.14]

normalization:
  filter_weight: 0.1
  clip_actions: 1.0
  clip_actions_method: "normal"

viewer:
  ref_env: 0
  pos: [10., 0., 6.]
  lookat: [11., 5., 3.]

sim:
  physics_engine: "SIM_PHYSX" # or "SIM_FLEX"
  dt: 0.002
  substeps: 1
  gravity: [0.0, 0.0, -9.81]
  up_axis: 1

  physx:
    num_subscenes: 0
    num_threads: 4
    solver_type: 1
    num_position_iterations: 4
    num_velocity_iterations: 1
    contact_offset: 0.02
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1.0
    max_gpu_contact_pairs: 8_388_608 # 2^23
    default_buffer_size_multiplier: 5.0
    contact_collection: 2

policy:
  class_name: "RecurrentModel"
  learning_rate: 1.e-5
  desired_kl: 0.01
  obs_key: "student_observations"
  params:
    layer_activation: "elu"
    recurrent_state_size: 256
    hidden_layer_sizes: [256, 128]
    symlog_inputs: True
    normalize_obs: True
    head: {output_type: normal_logstdparam_unclipped, minstd: 0.02, maxstd: 1.0, outscale: 1.0, init_std: 0.30}

value:
  class_name: "RecurrentModel"
  learning_rate: 3.e-4
  obs_key: "teacher_observations"
  params:
    layer_activation: "elu"
    recurrent_state_size: 512
    hidden_layer_sizes: [512, 256, 128]
    symlog_inputs: True
    normalize_obs: True
    head: {output_type: mse, outscale: 1.0}

algorithm:
  gamma: 0.97
  lam: 0.95
  entropy_coef: -0.01
  symmetry: True
  symmetry_coef: 3.0
  num_learning_epochs: 5
  num_mini_batches: 4
  value_loss_coef: 1.0
  use_clipped_value_loss: False
  clip_param: 0.2
  bound_coef: 1.0
  normalize_advantage_per_minibatch: True

runner:
  record_video: False
  record_distance: [-1.8, -1.8, 0.5]
  num_steps_per_env: 24
  class_name: "Runner"
  use_wandb: True
  description: ""
  log_every: 30.
  save_every: 150.
  record_every: 600.
  record_frames: 300.
  run_name: ""
  resume: False
  load_run: ""
  checkpoint: -1
  resume_path: ""
  max_iterations: 10000
