seed: -1
task: 'anymal_c'
print_config: False
rl_device: 'cuda:0'
sim_device: 'cuda:0'
graphics_device: 'cuda:0'
headless: False
logdir: 'default'
multi_gpu: False
multi_gpu_global_rank: 0
multi_gpu_local_rank: 0
multi_gpu_world_size: 1
master_addr: '127.0.0.1'

env:
  num_envs: 2048
  send_timeouts: True # For value bootstrap.
  episode_length_s: 40.

  force_renderer: False
  camera_params:
    # Original intrinsics.
    cam_width: 320
    cam_height: 240
    fl_x: 303.0424
    fl_y: 303.1759
    pp_x: 161.5755
    pp_y: 124.6430

    # How much to downscale the image (and intrinsics) by.
    downscale_factor: 5.0

    # Cam offset relative to `asset.camera_link_name`.
    cam_xyz_offset: [
        0.44665475921048414,
        0.009719827812061002,
        0.17764090819492523,
      ] # Local frame: [x, y, z] meters.
    cam_rpy_offset: [1.571, 1.571, 3.142]

observations:
  critic:
    observations:
      [
        BASE_LIN_VEL,
        BASE_ANG_VEL,
        PROJECTED_GRAVITY,
        VELOCITY_COMMANDS,
        DOF_POS,
        DOF_VEL,
        ACTIONS,
        RAY_CAST,
        BASE_MASS_SCALED,
        PUSHING_FORCES,
        PUSHING_TORQUES,
      ]
  policy:
    add_noise: True
    add_latency: True
    latency_resampling_interval_s: 3.0
    observations:
      [
        BASE_ANG_VEL,
        PROJECTED_GRAVITY,
        VELOCITY_COMMANDS,
        DOF_POS,
        DOF_VEL,
        ACTIONS,
      ]
    sync_latency:
      [BASE_ANG_VEL, PROJECTED_GRAVITY, VELOCITY_COMMANDS, DOF_POS, DOF_VEL]

terrain:
  scene_root: '{GAUSS_GYM_ROOT_DIR}/scenes'
  cams_yaw_only: False
  static_friction: 1.0
  dynamic_friction: 1.0
  restitution: 0.
  num_mesh_repeats: 1

  scenes:
    max_num_scenes: 10
    iphone_data:
      class_name: GaussGymData
      split_frac: 1.0
      repo_id: 'escontra/gauss_gym_data'
      scene: ''
    grand_tour:
      class_name: GrandTourData
      split_frac: 0.0
      mission: ''
    arkit:
      class_name: ARKitData
      split_frac: 0.0
      split: 'Training'

init_state:
  pos: [0.0, 0.0, 0.7]
  rot: [0.0, 0.0, 0.0, 1.0]
  lin_vel: [0.0, 0.0, 0.0]
  ang_vel: [0.0, 0.0, 0.0]
  default_joint_angles:
    {
      'LF_HAA': 0.0,
      'LH_HAA': 0.0,
      'RF_HAA': -0.0,
      'RH_HAA': -0.0,
      'LF_HFE': 0.4,
      'LH_HFE': -0.4,
      'RF_HFE': 0.4,
      'RH_HFE': -0.4,
      'LF_KFE': -0.8,
      'LH_KFE': 0.8,
      'RF_KFE': -0.8,
      'RH_KFE': 0.8,
    }

control:
  control_type: 'P'
  stiffness: { 'HAA': 80., 'HFE': 80., 'KFE': 80. } # [N*m/rad]
  damping: { 'HAA': 2., 'HFE': 2., 'KFE': 2. } # [N*m*s/rad]
  decimation: 4
  use_actuator_network: True
  actuator_net_file: '{GAUSS_GYM_ROOT_DIR}/resources/actuator_nets/anydrive_v3_lstm.pt'
  computer_clip_torque: False
  motor_clip_torque: False

asset:
  file: '{GAUSS_GYM_ROOT_DIR}/resources/robots/anymal_c/urdf/anymal_c.urdf'
  name: 'anymal_c'
  base_link_name: 'base'
  camera_link_name: 'base'
  foot_name: 'FOOT'
  hip_link_names: ['RF_HAA', 'LF_HAA', 'RH_HAA', 'LH_HAA']
  front_hip_names: ['base_RF_HAA', 'base_LF_HAA']
  rear_hip_names: ['base_RH_HAA', 'base_LH_HAA']
  penalize_contacts_on: ['SHANK', 'THIGH']
  terminate_after_contacts_on: ['base']
  feet_edge_pos: [[0.0, 0.0, 0.0225]]
  feet_contact_radius: 0.031

  disable_joint_limits: False
  disable_gravity: False
  collapse_fixed_joints: True
  fix_base_link: False
  default_dof_drive_mode: 3
  self_collisions: 1
  replace_cylinder_with_capsule: True
  flip_visual_attachments: True

  density: 0.001
  angular_damping: 0.
  linear_damping: 0.
  max_angular_velocity: 1000.
  max_linear_velocity: 1000.
  armature: 0.
  thickness: 0.01

domain_rand:
  apply_domain_rand: True

  camera_refresh_interval_s: 3.0
  # Refresh duration. How often the camera image is refreshed.
  # Not to be confused with the sythetic refresh_duration used in
  # observation_manager.
  refresh_duration:
    apply: True
    range: [0.05, 0.15]
    operation: 'additive'
    distribution: 'uniform'
  focal_length:
    apply: True
    range: [0.0, 3.0]
    operation: 'additive'
    distribution: 'gaussian'
  principal_point:
    apply: True
    range: [0.0, 1.0]
    operation: 'additive'
    distribution: 'gaussian'
  camera_pos:
    apply: True
    range: [-0.02, 0.02]
    operation: 'additive'
    distribution: 'uniform'
  camera_rot:
    apply: True
    range: [-0.03, 0.03]
    operation: 'additive'
    distribution: 'uniform'

  init_dof_pos:
    apply: True
    range: [0.0, 0.05]
    operation: 'additive'
    distribution: 'gaussian'
  init_base_lin_vel_xy:
    apply: True
    range: [0.0, 0.1]
    operation: 'additive'
    distribution: 'gaussian'
  init_base_yaw:
    apply: True
    range: [0.0, 1.5]
    operation: 'additive'
    distribution: 'gaussian'

  base_com_x:
    apply: True
    range: [-0.1, 0.1]
    operation: 'additive'
    distribution: 'uniform'
  base_com_y:
    apply: True
    range: [-0.1, 0.1]
    operation: 'additive'
    distribution: 'uniform'
  base_com_z:
    apply: True
    range: [-0.05, 0.05]
    operation: 'additive'
    distribution: 'uniform'
  base_mass:
    apply: True
    range: [0.8, 1.2]
    operation: 'scaling'
    distribution: 'uniform'
  other_com:
    apply: True
    range: [-0.005, 0.005]
    operation: 'additive'
    distribution: 'uniform'
  other_mass:
    apply: True
    range: [0.9, 1.1]
    operation: 'scaling'
    distribution: 'uniform'

  motor_strength:
    apply: True
    range: [0.8, 1.2]
    operation: 'scaling'
    distribution: 'uniform'
  motor_error:
    apply: True
    range: [-0.03, 0.03]
    operation: 'additive'
    distribution: 'uniform'

  dof_stiffness:
    apply: True
    range: [0.9, 1.1]
    operation: 'scaling'
    distribution: 'uniform'
  dof_damping:
    apply: True
    range: [0.95, 1.05]
    operation: 'scaling'
    distribution: 'uniform'
  dof_damping_ankles:
    apply: False
    ankle_names:
      [
        'Left_Ankle_Pitch',
        'Right_Ankle_Pitch',
        'Left_Ankle_Roll',
        'Right_Ankle_Roll',
      ]
    range: [-0.5, 2.0]
    operation: 'additive'
    distribution: 'uniform'
  dof_friction:
    apply: False
    range: [0.0, 2.0]
    operation: 'additive'
    distribution: 'uniform'
  dof_friction_ig_property:
    apply: True
    range: [0.0, 0.05]
    operation: 'additive'
    distribution: 'uniform_buckets'
    buckets: 255
  dof_armature_ig_property:
    apply: True
    range: [0.0, 0.015]
    operation: 'additive'
    distribution: 'uniform'

  foot_friction:
    apply: True
    range: [0.3, 2.0]
    operation: 'additive'
    distribution: 'uniform'
  foot_compliance:
    apply: True
    range: [0.5, 1.5]
    operation: 'additive'
    distribution: 'uniform'
  foot_restitution:
    apply: True
    range: [0.1, 0.9]
    operation: 'additive'
    distribution: 'uniform'

  kick_interval_s: 4.0
  kick_lin_vel:
    apply: True
    range: [-1.5, 1.5]
    operation: 'additive'
    distribution: 'uniform'
  kick_ang_vel:
    apply: True
    range: [-1.5, 1.5]
    operation: 'additive'
    distribution: 'uniform'

  push_interval_s: 8.0
  push_duration_s: 1.0
  push_force:
    apply: True
    range: [0., 10.]
    operation: 'additive'
    distribution: 'gaussian'
  push_torque:
    apply: True
    range: [0., 2.]
    operation: 'additive'
    distribution: 'gaussian'

termination:
  base_height_threshold: 0.5
  projected_gravity_z_threshold: 0.0

commands:
  name: 'goal'

  command_gains: False
  command_gains_stiffness_range: [0.8, 1.2]
  command_gains_damping_range: [0.8, 1.2]
  gait_frequency: [0.8, 1.2]

  velocity:
    use_ground_positions: True
    lin_vel_range: [0.1, 0.7]
    ang_vel_yaw_range: [-1, 1]

    max_traj_pos_distance: 1.0
    max_traj_yaw_distance_rad: 6.28
    still_proportion: 0.05

    resampling_time: 4.

    small_lin_vel_threshold: 0.0
    small_ang_vel_threshold: 0.0

    success_on_loop: False
    truncate_on_success: True

  goal:
    goal_window_s: [10.0, 20.0]
    use_ground_positions: True

    goal_xyz: False
    goal_distance: 5.0
    goal_evaluation_time_s: 1.0
    goal_reached_pos_only: True
    goal_reached_pos_threshold: 0.25
    goal_reached_yaw_threshold: 0.5
    random_heading_goal: True

    distance_curriculum: True
    distance_schedule: [0.5, 10.0]
    completion_up_threshold: 0.7
    distance_up_amount: 0.5

rewards:
  only_positive_rewards: False
  scale_by_dt: False

  task:
    velocity:
      vel_tracking.scale: 1.0
      vel_tracking.tracking_sigma: 0.25
      yaw_vel_tracking.scale: 0.5
      yaw_vel_tracking.tracking_sigma: 0.25
    goal:
      pos_tracking.scale: 10.0
      yaw_tracking.scale: 5.0
      stand_at_target.scale: 0.0
      move_in_direction.scale: 1.0
      dont_wait.scale: -1.0
      dont_wait.vel_threshold: 0.2
  lin_vel_z.scale: -0.5
  ang_vel_xy.scale: -0.05
  torques.scale: -0.00001
  dof_acc.scale: -2.5e-7
  feet_air_time.scale: 1.0
  feet_air_time.min_air_time: 0.5
  feet_air_time.max_air_time: 1.5
  collision.scale: -1.0
  action_rate.scale: -0.01
  action_rate.use_action_mean: False

reward_penalty_curriculum:
  apply: False
  init_penalty_scale: 0.5
  min_penalty_scale: 0.1
  max_penalty_scale: 1.0
  min_episodes: 20
  completion_down_threshold: 0.3
  completion_up_threshold: 0.7
  percent_change: 0.05

  keys:
    [
      goal.stand_at_target,
      ang_vel_xy,
      orientation,
      action_rate,
      base_height,
      t1_pose,
      feet_distance,
    ]


# rewards:
#   only_positive_rewards: True
#   tracking_sigma: 0.25
#   soft_dof_pos_limit: 1.0
#   soft_dof_vel_limit: 1.0
#   soft_torque_limit: 1.0
#   base_height_target: 0.5
#   max_contact_force: 500.0
#   terminate_height: 0.08
#   feet_air_time_min_time: 0.5
#   feet_air_time_max_time: 1.5
#   scales:
#     termination: -0.
#     tracking_lin_vel: 0.0
#     tracking_lin_vel_x: 1.0
#     tracking_lin_vel_y: 1.0
#     tracking_ang_vel: 0.5
#     lin_vel_z: -0.5
#     ang_vel_xy: -0.05
#     orientation: -0.
#     torques: -0.00001
#     dof_vel: -0.
#     dof_acc: -2.5e-7
#     base_height: -0.
#     feet_air_time:  1.0
#     collision: -1.
#     feet_stumble: -0.0
#     action_rate: -0.01
#     stand_still: -0.

normalization:
  filter_weight: 0.1

viewer:
  ref_env: 0
  pos: [10., 0., 6.]
  lookat: [11., 5., 3.]

sim:
  physics_engine: 'SIM_PHYSX' # or "SIM_FLEX"
  dt: 0.005
  substeps: 1
  gravity: [0.0, 0.0, -9.81]
  up_axis: 1

  physx:
    num_subscenes: 0
    num_threads: 10
    solver_type: 1
    num_position_iterations: 4
    num_velocity_iterations: 0
    contact_offset: 0.01
    rest_offset: 0.0
    bounce_threshold_velocity: 0.5
    max_depenetration_velocity: 1.0
    max_gpu_contact_pairs: 8_388_608 # 2^23
    default_buffer_size_multiplier: 5
    contact_collection: 2

image_encoder:
  class_name: RecurrentCNNModel
  freeze_encoder: True
  obs_key: image_encoder
  reconstruct_observations:
    [critic/RAY_CAST, critic/BASE_ANG_VEL, critic/BASE_LIN_VEL]
  voxel_height_levels: 24
  num_updates_range: [1, 100]
  init_num_updates: 20
  num_steps_per_env: 10
  train_ratio_scheduler:
    warmup_steps: 100
    train_ratio_warmup: 1.0
    train_ratio_after: 0.1
  learning_rate_scheduler:
    warmup_steps: 100
    learning_rate_warmup: 1.e-4
    learning_rate_after: 5.e-5
  params:
    layer_activation: silu
    recurrent_state_size: 512
    recurrent_skip_connection: True
    hidden_layer_sizes: [512, 256, 256]
    symlog_inputs: True
    normalize_obs: True
    from_local: True
    model_type: timm_test_convnext.r160_in1k
    embedding_dim: 128
    torchaug_transforms: True

policy:
  class_name: RecurrentMLPModel
  project_image_encoder_latent: True
  project_image_encoder_latent_dim: 32
  learning_rate: 1.e-5
  obs_key: policy
  params:
    layer_activation: silu
    recurrent_state_size: 256
    recurrent_skip_connection: True
    hidden_layer_sizes: [256, 128]
    symlog_inputs: True
    normalize_obs: True
    head:
      actions:
        class_name: NormalLogSTDHead
        params:
          minstd: 0.04
          maxstd: 1.0
          init_std: 0.3
          outscale: 0.01
      stiffness:
        class_name: NormalLogSTDHead
        params:
          minstd: 0.05
          maxstd: 1.0
          init_std: 0.1
          bounded: True
          outscale: 0.01
      damping:
        class_name: NormalLogSTDHead
        params:
          minstd: 0.05
          maxstd: 1.0
          init_std: 0.1
          bounded: True
          outscale: 0.01

value:
  class_name: RecurrentMLPModel
  project_image_encoder_latent: True
  project_image_encoder_latent_dim: 32
  learning_rate: 3.e-4
  obs_key: critic
  params:
    layer_activation: silu
    recurrent_state_size: 512
    recurrent_skip_connection: True
    hidden_layer_sizes: [512, 256, 128]
    symlog_inputs: True
    normalize_obs: True
    head:
      value:
        class_name: TwoHotHead
        params:
          outscale: 0.0
          bins: 254

algorithm:
  gamma: 0.97
  lam: 0.95
  actor_loss_coefs:
    actions: 1.0
    stiffness: 0.1
    damping: 0.1
  entropy_coefs:
    actions: -0.01
    stiffness: -0.001
    damping: -0.001
  desired_kl: 0.01
  kl_adjust_value_lr: False
  kl_key: actions
  symmetry_loss: False
  symmetry_augmentation: False
  symmetry_flip_latents: True
  symmetry_coefs:
    actions: 3.0
    stiffness: 3.0
    damping: 3.0
  num_learning_epochs: 5
  num_mini_batches: 4
  value_loss_coef: 1.0
  use_clipped_value_loss: False
  clip_param: 0.2
  bound_coefs:
    actions: 0.0
  train_image_encoder: False
  image_encoder_batch_size: 48
  normalize_rewards: False
  pmpo_advantages: False

runner:
  record_video: False
  record_distance: [-1.8, -1.8, 0.5]
  num_steps_per_env: 24
  class_name: Runner
  use_wandb: False
  wandb_save_model: True
  description: ''
  log_every: 120.
  save_every: 3600.
  record_every: 3600.
  record_frames: 300.
  run_name: ''
  resume: False
  load_run: ''
  checkpoint: -1
  resume_path: ''
  max_iterations: 30000
  share_url: False
